theme: jekyll-theme-minimal
# Site settings
title: Wenjing Pan
email: wjpan@ucdavis.edu
description: > # this means to ignore newlines until "baseurl:"
    I'm a communication scholar interested in social support and computational social science. 
github_username:  wenjingpan
permalink: /blog/:year/:month/:title.html
gems:
    - jekyll-sitemap

# Build settings
markdown: kramdown
